### ISSUE TITLE
Setup the KANBAN-BOARD

### ISSUE THREAD

**Issue by Tobinchilongo** [Tobinchilongo/Final-Capstone-BackEnd#19]
- In this final group capstone, We are a team of 4(Four) members 
        1.       @jerryowusu 
        2.       @cynthiainga 
        3.       @Tobinchilongo 
        4.       @Fikerte-T 
- And we have therefore decided to go with the Car rental app.
- Also, There are two Repositories in our project, Front-End as well as Back-End
- Here is the [Repo Link](https://github.com/jerryowusu/final-capstone-frontend
) to the Front-End project.

**Here is the [link](https://github.com/Tobinchilongo/Final-Capstone-BackEnd/projects/1) to our project: Kanban-Board-Setup**

Below is a screenshot of our Kanban Board
![Screenshot](https://user-images.githubusercontent.com/88584398/177570946-1b8e9c7c-32f9-4f52-bc6b-33ad975a2079.png)

**Comment by vichuge** [comment]
Hi dear student, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by jerryowusu** [comment]
Thanks @vichuge
